spring.application.name=Smart_Phone_Shop

#spring.jpa.hibernate.ddl-auto = none
#spring.jpa.hibernate.ddl-auto = create
spring.jpa.hibernate.ddl-auto = update
#spring.jpa.hibernate.ddl-auto = create-drop

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.enable_lazy_load_no_trans = true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.profiles.active=dev

# C?u hình các tài nguyên t?nh và th? m?c upload
spring.web.resources.static-locations=file:./uploads/,classpath:/static/

# C?u hình upload file
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

paypal.client.id=AXBTSV0r2LIggE6o5iTeP9lcOXCHLCcLt6Gq4HmZTgZsFnmogPAIjTXF-usf9in5yEHcsPEjrFAWP_V6
paypal.client.secret=EJk9cXkWkiZ-5f5J61KQxnj3lb1vrfzGWKjPl7cZ-fuj7vdNiaxqWmzuhK9kQ8noD4CT_iKoBW6G0GpC
paypal.mode=sandbox
paypal.return.url=http://localhost:8080/user/checkout/paypal/success
paypal.cancel.url=http://localhost:8080/user/checkout/paypal/cancel